spring:
  application:
    name: feign-client1
#admin的客户端不需要配置权限控制
#  security:
#    user:
#      name: client
#      password: client
server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: "*"
#logging:
#  file: var/log/eureka-client.log
#  pattern:
#    file: clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    metadata-map:
      user.name:  ${spring.security.user.name}
      user.password:  ${spring.security.user.password}
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:7001/eureka/

feign:
  client:
    config:
      feign-service1:
        ConnectTimeout: 5000
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 2
        OkToRetryOnAllOperations: true
        ReadTimeout: 3000


#feign-service1:
#  ribbion:
#    ConnectTimeout: 500
#    MaxAutoRetries: 1
#    MaxAutoRetriesNextServer: 2
#    OkToRetryOnAllOperations: true
#    ReadTimeout: 2000

#hystrix:
#  command:
#    default:  #default全局有效，service id指定应用有效
#      execution:
#        timeout:
#          #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
#          enabled: true
#        isolation:
#          thread:
#            timeoutInMilliseconds: 1000 #断路器超时时间，默认1000ms
#
#feign.hystrix.enabled: true

