spring:
  application:
    name: feign-service1
#admin的客户端不需要配置权限控制
#  security:
#    user:
#      name: client
#      password: client
server:
  port: 8087

management:
  endpoints:
    web:
      exposure:
        include: "*"
#logging:
#  file: var/log/eureka-client.log
#  pattern:
#    file: clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    prefer-ip-address: true
#    metadata-map:
#      user.name:  ${spring.security.user.name}
#      user.password:  ${spring.security.user.password}
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:7001/eureka/

