spring:
  application:
    name: feign-service1
#admin的客户端不需要配置权限控制
#  security:
#    user:
#      name: client
#      password: client
server:
  port: 8087
#打开feign
feign:
  hystrix:
    enabled: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    ip-address: 192.168.88.38
    hostname: ${eureka.instance.ip-address}
    instance-id: ${eureka.instance.ip-address}:${server.port}
#    metadata-map:
#      user.name:  ${spring.security.user.name}
#      user.password:  ${spring.security.user.password}
  client:
    registryFetchIntervalSeconds: 30
    service-url:
      defaultZone: http://eureka.didispace.com/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
      health:
        show-details: ALWAYS
#logging:
#  file: var/log/eureka-client.log
#  pattern:
#    file: clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx
